apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kartograph-sso-client-swagger-docs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: kartograph-sso-client-swagger-docs
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: kartograph/stage/sso-clients/swagger-docs
