# Development overrides for compose.yaml
services:
  api:
    # Run as root in dev to handle host file permissions (any umask)
    user: "${UID}:${GID}"
    volumes:
      # Mount the entire app directory  (minus  venv) for hot-reload
      - ./src/api:/app:z
      - /app/.venv
    command:
      - /bin/bash
      - -c
      - |
        uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
