apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kartograph-stage
resources:
  - ../../base
  - route.yaml
  - dev-ui-route.yaml
patches:
  - path: configmap-patch.yaml
  - path: resources-patch.yaml
images:
  - name: quay.io/redhat-user-workloads/kartograph-tenant/kartograph-api
    newTag: 3fc519cff2788c9ba8d83460f1253a4a1faf2530
  - name: quay.io/redhat-user-workloads/kartograph-tenant/kartograph-dev-ui
    newTag: 1fc3a330b83a58e1cf0617b9ead9f229a54d486d
