"""Unit tests for main FastAPI application configuration.

Tests for Swagger UI OAuth2/OIDC integration.
Following TDD approach - tests written before implementation.
"""

from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest
from fastapi import FastAPI
from pydantic import SecretStr


TEST_ISSUER = "https://auth.example.com/realms/test"
TEST_CLIENT_ID = "test-api-client"
TEST_CLIENT_SECRET = "test-secret"
TEST_SWAGGER_CLIENT_ID = "test-swagger-client"


@pytest.fixture
def mock_oidc_settings() -> MagicMock:
    """Create mock OIDC settings for testing."""
    settings = MagicMock()
    settings.issuer_url = TEST_ISSUER
    settings.client_id = TEST_CLIENT_ID
    settings.client_secret = SecretStr(TEST_CLIENT_SECRET)
    settings.swagger_client_id = TEST_SWAGGER_CLIENT_ID
    return settings


@pytest.fixture
def test_app() -> FastAPI:
    """Create a minimal test FastAPI app."""
    return FastAPI(
        title="Test API",
        version="1.0.0",
        description="Test application",
    )


class TestConfigureSwaggerOAuth2:
    """Tests for configure_swagger_oauth2 function.

    Note: The OAuth2 security scheme is now auto-generated by FastAPI's
    OAuth2AuthorizationCodeBearer when routes depend on it. These tests
    only verify the swagger_ui_init_oauth configuration.
    """

    def test_swagger_ui_init_oauth_configured_when_oidc_valid(
        self,
        test_app: FastAPI,
        mock_oidc_settings: MagicMock,
    ) -> None:
        """Swagger UI init oauth should be configured when OIDC settings are valid."""
        from main import configure_swagger_oauth2

        with patch("main.get_oidc_settings", return_value=mock_oidc_settings):
            configure_swagger_oauth2(test_app)

        assert test_app.swagger_ui_init_oauth is not None
        assert test_app.swagger_ui_init_oauth["clientId"] == TEST_SWAGGER_CLIENT_ID

    def test_pkce_enabled_in_swagger_config(
        self,
        test_app: FastAPI,
        mock_oidc_settings: MagicMock,
    ) -> None:
        """usePkceWithAuthorizationCodeGrant should be True."""
        from main import configure_swagger_oauth2

        with patch("main.get_oidc_settings", return_value=mock_oidc_settings):
            configure_swagger_oauth2(test_app)

        assert test_app.swagger_ui_init_oauth is not None
        assert (
            test_app.swagger_ui_init_oauth["usePkceWithAuthorizationCodeGrant"] is True
        )

    def test_swagger_not_configured_when_oidc_settings_fail(
        self,
        test_app: FastAPI,
    ) -> None:
        """Swagger OAuth2 should not be configured when OIDC settings fail."""
        from main import configure_swagger_oauth2

        with patch(
            "main.get_oidc_settings",
            side_effect=Exception("Missing client_secret"),
        ):
            configure_swagger_oauth2(test_app)

        # swagger_ui_init_oauth should remain None (not set)
        assert test_app.swagger_ui_init_oauth is None

    def test_scopes_configured_in_swagger_init(
        self,
        test_app: FastAPI,
        mock_oidc_settings: MagicMock,
    ) -> None:
        """Scopes should be configured in swagger_ui_init_oauth."""
        from main import configure_swagger_oauth2

        with patch("main.get_oidc_settings", return_value=mock_oidc_settings):
            configure_swagger_oauth2(test_app)

        assert test_app.swagger_ui_init_oauth is not None
        assert "scopes" in test_app.swagger_ui_init_oauth
        assert "openid" in test_app.swagger_ui_init_oauth["scopes"]

    def test_uses_public_swagger_client_not_api_client(
        self,
        test_app: FastAPI,
        mock_oidc_settings: MagicMock,
    ) -> None:
        """Should use the public swagger_client_id, not the confidential API client."""
        from main import configure_swagger_oauth2

        with patch("main.get_oidc_settings", return_value=mock_oidc_settings):
            configure_swagger_oauth2(test_app)

        assert test_app.swagger_ui_init_oauth is not None
        # Should use swagger_client_id, not client_id
        assert test_app.swagger_ui_init_oauth["clientId"] == TEST_SWAGGER_CLIENT_ID
        assert test_app.swagger_ui_init_oauth["clientId"] != TEST_CLIENT_ID
