#!/usr/bin/env bash
#
# Manages isolated Kartograph dev instances for parallel development.
#
# Each instance gets unique ports derived from a project name, its own
# Docker network and volumes, and a patched Keycloak realm. Multiple
# agents (or developers) can run instances simultaneously without
# port collisions.
#
# Usage:
#   ./scripts/dev-instance.sh up [--name <project>] [--no-keycloak] [--no-ui]
#   ./scripts/dev-instance.sh down [--name <project>]
#   ./scripts/dev-instance.sh status [--name <project>]
#   ./scripts/dev-instance.sh env [--name <project>]
#
# If --name is omitted, the project name is derived from the current
# directory basename (useful in worktrees where the dirname is unique).
#
# The --no-keycloak flag starts without Keycloak (for agent/CI use with
# the fake OIDC provider). This is the recommended mode for agents.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Defaults ---
PROJECT_NAME=""
NO_KEYCLOAK=false
NO_UI=true
ACTION=""

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        up|down|status|env)
            ACTION="$1"; shift ;;
        --name)
            PROJECT_NAME="$2"; shift 2 ;;
        --no-keycloak)
            NO_KEYCLOAK=true; shift ;;
        --no-ui)
            NO_UI=true; shift ;;
        --with-ui)
            NO_UI=false; shift ;;
        --with-keycloak)
            NO_KEYCLOAK=false; shift ;;
        *)
            echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

if [[ -z "$ACTION" ]]; then
    echo "Usage: $0 <up|down|status|env> [--name <project>] [--no-keycloak] [--no-ui]" >&2
    exit 1
fi

# --- Derive project name from directory if not provided ---
if [[ -z "$PROJECT_NAME" ]]; then
    PROJECT_NAME="$(basename "$(pwd)")"
fi

# Sanitize: lowercase, replace non-alphanumeric with dash
PROJECT_NAME="$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')"

# --- Compute deterministic port offset from project name ---
# Uses a simple hash to get a number 1-99, multiplied by 100 for port spacing.
# "kartograph" (the default dir) gets offset 0 (standard ports).
compute_offset() {
    local name="$1"
    if [[ "$name" == "kartograph" ]]; then
        echo 0
        return
    fi
    # CRC32-style hash → mod 99 + 1, then × 100
    local hash
    hash=$(echo -n "$name" | cksum | awk '{print $1}')
    local slot=$(( (hash % 99) + 1 ))
    echo $(( slot * 100 ))
}

OFFSET=$(compute_offset "$PROJECT_NAME")

# --- Compute ports ---
API_PORT=$(( 8000 + OFFSET ))
KEYCLOAK_PORT=$(( 8080 + OFFSET ))
KEYCLOAK_MGMT_PORT=$(( 9000 + OFFSET ))
POSTGRES_PORT=$(( 5432 + OFFSET ))
SPICEDB_PORT=$(( 50051 + OFFSET ))
FAKE_OIDC_PORT=$(( 8180 + OFFSET ))
DEVUI_PORT=$(( 3000 + OFFSET ))
HMR_PORT=$(( 24678 + OFFSET ))

# --- Instance directory for generated files ---
INSTANCE_DIR="$REPO_ROOT/.instances/$PROJECT_NAME"
mkdir -p "$INSTANCE_DIR"

# --- Generate compose override ---
generate_compose_override() {
    cat > "$INSTANCE_DIR/compose.override.yaml" << YAML
# Auto-generated by dev-instance.sh for project: $PROJECT_NAME
# Port offset: $OFFSET
services:
  keycloak:
    ports: !override
      - "${KEYCLOAK_PORT}:8080"
      - "${KEYCLOAK_MGMT_PORT}:9000"
    volumes:
      - ${INSTANCE_DIR}/realm.json:/opt/keycloak/data/import/realm.json:ro

  postgres:
    ports: !override
      - "${POSTGRES_PORT}:5432"

  spicedb:
    ports: !override
      - "${SPICEDB_PORT}:50051"

  fake-oidc:
    ports: !override
      - "${FAKE_OIDC_PORT}:8180"

  api:
    ports: !override
      - "${API_PORT}:8000"

  dev-ui:
    ports: !override
      - "${DEVUI_PORT}:3000"
      - "${HMR_PORT}:24678"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:${API_PORT}
      - NUXT_PUBLIC_MCP_ENDPOINT_URL=http://localhost:${API_PORT}/query/mcp
      - NUXT_PUBLIC_KEYCLOAK_URL=http://localhost:${KEYCLOAK_PORT}
YAML
}

# --- Generate patched Keycloak realm.json ---
generate_realm() {
    if [[ ! -f "$REPO_ROOT/keycloak/realm.json" ]]; then
        echo "Warning: keycloak/realm.json not found, skipping realm generation" >&2
        return
    fi
    # Patch redirect URIs and web origins to use instance-specific ports
    sed \
        -e "s|localhost:8000|localhost:${API_PORT}|g" \
        -e "s|127.0.0.1:8000|127.0.0.1:${API_PORT}|g" \
        -e "s|localhost:3000|localhost:${DEVUI_PORT}|g" \
        -e "s|127.0.0.1:3000|127.0.0.1:${DEVUI_PORT}|g" \
        "$REPO_ROOT/keycloak/realm.json" > "$INSTANCE_DIR/realm.json"
}

# --- Generate .env.instance for pytest/local use ---
generate_env() {
    cat > "$INSTANCE_DIR/.env.instance" << ENV
# Auto-generated by dev-instance.sh for project: $PROJECT_NAME
# Source this file to point local tools at this instance:
#   source .instances/$PROJECT_NAME/.env.instance

export KARTOGRAPH_DB_HOST=localhost
export KARTOGRAPH_DB_PORT=$POSTGRES_PORT
export KARTOGRAPH_DB_DATABASE=kartograph
export KARTOGRAPH_DB_USERNAME=kartograph
export KARTOGRAPH_DB_PASSWORD=kartograph_dev_password
export KARTOGRAPH_DB_GRAPH_NAME=kartograph_graph

export SPICEDB_ENDPOINT=localhost:$SPICEDB_PORT
export SPICEDB_PRESHARED_KEY=changeme
export SPICEDB_USE_TLS=true
export SPICEDB_CERT_PATH=$REPO_ROOT/certs/spicedb-cert.pem

export KARTOGRAPH_OIDC_CLIENT_ID=kartograph-api
export KARTOGRAPH_OIDC_CLIENT_SECRET=kartograph-api-secret

$(if [[ "$NO_KEYCLOAK" == "true" ]]; then
echo "export KARTOGRAPH_OIDC_ISSUER_URL=http://localhost:${FAKE_OIDC_PORT}/realms/kartograph"
else
echo "export KARTOGRAPH_OIDC_ISSUER_URL=http://localhost:${KEYCLOAK_PORT}/realms/kartograph"
fi)
ENV
}

# --- Build compose command ---
compose_cmd() {
    local cmd="docker compose -p kg-${PROJECT_NAME} -f $REPO_ROOT/compose.yaml"

    if [[ "$NO_KEYCLOAK" == "true" ]]; then
        cmd="$cmd -f $REPO_ROOT/compose.agent.yaml"
    fi

    cmd="$cmd -f $INSTANCE_DIR/compose.override.yaml"
    echo "$cmd"
}

# --- Actions ---
case "$ACTION" in
    up)
        echo "Starting Kartograph instance: $PROJECT_NAME"
        echo "  Port offset: $OFFSET"
        echo "  API:       http://localhost:$API_PORT"
        echo "  Postgres:  localhost:$POSTGRES_PORT"
        echo "  SpiceDB:   localhost:$SPICEDB_PORT"
        if [[ "$NO_KEYCLOAK" == "false" ]]; then
            echo "  Keycloak:  http://localhost:$KEYCLOAK_PORT"
        else
            echo "  Fake OIDC: http://localhost:$FAKE_OIDC_PORT"
        fi
        if [[ "$NO_UI" == "false" ]]; then
            echo "  Dev UI:    http://localhost:$DEVUI_PORT"
        fi
        echo ""

        # Generate configs
        generate_compose_override
        generate_realm
        generate_env

        # Ensure certs exist
        make -C "$REPO_ROOT" certs 2>/dev/null

        # Build and start
        local_cmd="$(compose_cmd)"

        if [[ "$NO_KEYCLOAK" == "true" && "$NO_UI" == "false" ]]; then
            $local_cmd --profile ui up -d --scale keycloak=0
        elif [[ "$NO_KEYCLOAK" == "true" ]]; then
            $local_cmd up -d --scale keycloak=0
        elif [[ "$NO_UI" == "false" ]]; then
            $local_cmd --profile ui up -d
        else
            $local_cmd up -d
        fi

        echo ""
        echo "Instance '$PROJECT_NAME' is starting."
        echo "To point tests at this instance:"
        echo "  source .instances/$PROJECT_NAME/.env.instance"
        ;;

    down)
        echo "Stopping Kartograph instance: $PROJECT_NAME"
        docker compose -p "kg-${PROJECT_NAME}" down 2>/dev/null || true
        ;;

    status)
        docker compose -p "kg-${PROJECT_NAME}" ps
        ;;

    env)
        # Print env vars for sourcing (useful for CI/scripts)
        generate_env >/dev/null 2>&1
        echo "KARTOGRAPH_DB_PORT=$POSTGRES_PORT"
        echo "SPICEDB_ENDPOINT=localhost:$SPICEDB_PORT"
        if [[ "$NO_KEYCLOAK" == "true" ]]; then
            echo "KARTOGRAPH_OIDC_ISSUER_URL=http://localhost:${FAKE_OIDC_PORT}/realms/kartograph"
        else
            echo "KARTOGRAPH_OIDC_ISSUER_URL=http://localhost:${KEYCLOAK_PORT}/realms/kartograph"
        fi
        echo "API_URL=http://localhost:$API_PORT"
        ;;
esac
